[[0, 0, 0], 16.666666666666664, {"submitted": 1589640326.5774245, "started": 1589640326.5774772, "finished": 1589640326.882649}, null, "Traceback (most recent call last):\n  File \"/home/shuki/anaconda3/envs/CAVE/lib/python3.8/site-packages/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/home/shuki/Repos/Auto-PyTorch/autoPyTorch/core/worker.py\", line 86, in compute\n    raise Exception(\"Exception in train pipeline. Took \" + str((time.time()-start_time)) + \" seconds with budget \" + str(budget))\nException: Exception in train pipeline. Took 0.30079030990600586 seconds with budget 16.666666666666664\n"]
[[0, 0, 1], 16.666666666666664, {"submitted": 1589640326.8905902, "started": 1589640326.890848, "finished": 1589640335.0896363}, {"loss": -67.51851851851852, "info": {"loss": 0.6225945949554443, "model_parameters": 50790.0, "lr_scheduler_converged": 0.0, "lr": 0.014735864703130869, "train_accuracy": 60.67415730337079, "val_accuracy": 68.51851851851852, "test_result": 70.0, "test_cross_entropy": 0.5964623093605042, "test_balanced_accuracy": 0.5}}, null]
[[0, 0, 2], 16.666666666666664, {"submitted": 1589640335.0943098, "started": 1589640335.0943825, "finished": 1589640335.3788488}, null, "Traceback (most recent call last):\n  File \"/home/shuki/anaconda3/envs/CAVE/lib/python3.8/site-packages/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/home/shuki/Repos/Auto-PyTorch/autoPyTorch/core/worker.py\", line 86, in compute\n    raise Exception(\"Exception in train pipeline. Took \" + str((time.time()-start_time)) + \" seconds with budget \" + str(budget))\nException: Exception in train pipeline. Took 0.28042101860046387 seconds with budget 16.666666666666664\n"]
[[0, 0, 1], 50.0, {"submitted": 1589640335.3827925, "started": 1589640335.3828704, "finished": 1589640376.6686497}, {"loss": -70.11111111111111, "info": {"loss": 0.5225832015275955, "model_parameters": 50790.0, "lr_scheduler_converged": 0.0, "lr": 0.010079640866897513, "train_accuracy": 69.66292134831461, "val_accuracy": 71.11111111111111, "test_result": 74.0, "test_cross_entropy": 0.5784512758255005, "test_balanced_accuracy": 0.6452380952380953}}, null]
[[1, 0, 0], 50.0, {"submitted": 1589640376.6762652, "started": 1589640376.676349, "finished": 1589640418.2615452}, {"loss": -66.03703703703704, "info": {"loss": 0.6576851904392242, "model_parameters": 2791775.0, "lr_scheduler_converged": 0.0, "lr": 0.0033211036217254807, "train_accuracy": 59.0, "val_accuracy": 67.03703703703704, "test_result": 63.0, "test_cross_entropy": 0.6729158163070679, "test_balanced_accuracy": 0.4904761904761905}}, null]
[[1, 0, 1], 50.0, {"submitted": 1589640418.2653103, "started": 1589640418.2653716, "finished": 1589640418.547368}, null, "Traceback (most recent call last):\n  File \"/home/shuki/anaconda3/envs/CAVE/lib/python3.8/site-packages/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/home/shuki/Repos/Auto-PyTorch/autoPyTorch/core/worker.py\", line 86, in compute\n    raise Exception(\"Exception in train pipeline. Took \" + str((time.time()-start_time)) + \" seconds with budget \" + str(budget))\nException: Exception in train pipeline. Took 0.27803635597229004 seconds with budget 50.0\n"]
[[2, 0, 0], 16.666666666666664, {"submitted": 1589640418.5540574, "started": 1589640418.5541465, "finished": 1589640418.9342804}, null, "Traceback (most recent call last):\n  File \"/home/shuki/anaconda3/envs/CAVE/lib/python3.8/site-packages/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/home/shuki/Repos/Auto-PyTorch/autoPyTorch/core/worker.py\", line 86, in compute\n    raise Exception(\"Exception in train pipeline. Took \" + str((time.time()-start_time)) + \" seconds with budget \" + str(budget))\nException: Exception in train pipeline. Took 0.3744041919708252 seconds with budget 16.666666666666664\n"]
[[2, 0, 1], 16.666666666666664, {"submitted": 1589640418.9405544, "started": 1589640418.9406526, "finished": 1589640419.2043686}, null, "Traceback (most recent call last):\n  File \"/home/shuki/anaconda3/envs/CAVE/lib/python3.8/site-packages/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/home/shuki/Repos/Auto-PyTorch/autoPyTorch/core/worker.py\", line 86, in compute\n    raise Exception(\"Exception in train pipeline. Took \" + str((time.time()-start_time)) + \" seconds with budget \" + str(budget))\nException: Exception in train pipeline. Took 0.25757360458374023 seconds with budget 16.666666666666664\n"]
[[2, 0, 2], 16.666666666666664, {"submitted": 1589640419.213945, "started": 1589640419.2140474, "finished": 1589640419.6068642}, null, "Traceback (most recent call last):\n  File \"/home/shuki/anaconda3/envs/CAVE/lib/python3.8/site-packages/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/home/shuki/Repos/Auto-PyTorch/autoPyTorch/core/worker.py\", line 86, in compute\n    raise Exception(\"Exception in train pipeline. Took \" + str((time.time()-start_time)) + \" seconds with budget \" + str(budget))\nException: Exception in train pipeline. Took 0.38468194007873535 seconds with budget 16.666666666666664\n"]
[[2, 1, 0], 50.0, {"submitted": 1589640419.6148756, "started": 1589640419.615029, "finished": 1589640420.2029977}, null, "Traceback (most recent call last):\n  File \"/home/shuki/anaconda3/envs/CAVE/lib/python3.8/site-packages/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/home/shuki/Repos/Auto-PyTorch/autoPyTorch/core/worker.py\", line 86, in compute\n    raise Exception(\"Exception in train pipeline. Took \" + str((time.time()-start_time)) + \" seconds with budget \" + str(budget))\nException: Exception in train pipeline. Took 0.5816512107849121 seconds with budget 50.0\n"]
[[3, 0, 0], 50.0, {"submitted": 1589640420.2108467, "started": 1589640420.2109628, "finished": 1589640461.5643158}, {"loss": -70.11111111111111, "info": {"loss": 0.24919410049915314, "model_parameters": 99178.0, "lr_scheduler_converged": 0.0, "lr": 0.00012998780665917557, "train_accuracy": 91.81818181818183, "val_accuracy": 71.11111111111111, "test_result": 69.0, "test_cross_entropy": 0.5562108159065247, "test_balanced_accuracy": 0.5595238095238095}}, null]
[[3, 0, 1], 50.0, {"submitted": 1589640461.572188, "started": 1589640461.572272, "finished": 1589640461.831012}, null, "Traceback (most recent call last):\n  File \"/home/shuki/anaconda3/envs/CAVE/lib/python3.8/site-packages/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/home/shuki/Repos/Auto-PyTorch/autoPyTorch/core/worker.py\", line 86, in compute\n    raise Exception(\"Exception in train pipeline. Took \" + str((time.time()-start_time)) + \" seconds with budget \" + str(budget))\nException: Exception in train pipeline. Took 0.253154993057251 seconds with budget 50.0\n"]
[[4, 0, 0], 16.666666666666664, {"submitted": 1589640461.8399394, "started": 1589640461.840111, "finished": 1589640469.8858387}, {"loss": -67.51851851851852, "info": {"loss": 0.6641953786214193, "model_parameters": 9592.0, "lr_scheduler_converged": 0.0, "lr": 0.0001621045765817548, "train_accuracy": 69.87951807228916, "val_accuracy": 68.51851851851852, "test_result": 70.0, "test_cross_entropy": 0.6767829060554504, "test_balanced_accuracy": 0.5}}, null]
[[4, 0, 1], 16.666666666666664, {"submitted": 1589640469.8907447, "started": 1589640469.8908286, "finished": 1589640470.2805643}, null, "Traceback (most recent call last):\n  File \"/home/shuki/anaconda3/envs/CAVE/lib/python3.8/site-packages/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/home/shuki/Repos/Auto-PyTorch/autoPyTorch/core/worker.py\", line 86, in compute\n    raise Exception(\"Exception in train pipeline. Took \" + str((time.time()-start_time)) + \" seconds with budget \" + str(budget))\nException: Exception in train pipeline. Took 0.38246631622314453 seconds with budget 16.666666666666664\n"]
[[4, 0, 2], 16.666666666666664, {"submitted": 1589640470.2886388, "started": 1589640470.2887437, "finished": 1589640470.7666888}, null, "Traceback (most recent call last):\n  File \"/home/shuki/anaconda3/envs/CAVE/lib/python3.8/site-packages/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/home/shuki/Repos/Auto-PyTorch/autoPyTorch/core/worker.py\", line 86, in compute\n    raise Exception(\"Exception in train pipeline. Took \" + str((time.time()-start_time)) + \" seconds with budget \" + str(budget))\nException: Exception in train pipeline. Took 0.47255587577819824 seconds with budget 16.666666666666664\n"]
[[4, 0, 0], 50.0, {"submitted": 1589640470.7698023, "started": 1589640470.769879, "finished": 1589640512.021877}, {"loss": -67.51851851851852, "info": {"loss": 0.6442435383796692, "model_parameters": 9592.0, "lr_scheduler_converged": 0.0, "lr": 4.833303591563336e-07, "train_accuracy": 64.45783132530121, "val_accuracy": 68.51851851851852, "test_result": 70.0, "test_cross_entropy": 0.6533401608467102, "test_balanced_accuracy": 0.5}}, null]
[[5, 0, 0], 50.0, {"submitted": 1589640512.025952, "started": 1589640512.0260293, "finished": 1589640512.495011}, null, "Traceback (most recent call last):\n  File \"/home/shuki/anaconda3/envs/CAVE/lib/python3.8/site-packages/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/home/shuki/Repos/Auto-PyTorch/autoPyTorch/core/worker.py\", line 86, in compute\n    raise Exception(\"Exception in train pipeline. Took \" + str((time.time()-start_time)) + \" seconds with budget \" + str(budget))\nException: Exception in train pipeline. Took 0.46210265159606934 seconds with budget 50.0\n"]
[[5, 0, 1], 50.0, {"submitted": 1589640512.5017564, "started": 1589640512.501833, "finished": 1589640512.893632}, null, "Traceback (most recent call last):\n  File \"/home/shuki/anaconda3/envs/CAVE/lib/python3.8/site-packages/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/home/shuki/Repos/Auto-PyTorch/autoPyTorch/core/worker.py\", line 86, in compute\n    raise Exception(\"Exception in train pipeline. Took \" + str((time.time()-start_time)) + \" seconds with budget \" + str(budget))\nException: Exception in train pipeline. Took 0.3872246742248535 seconds with budget 50.0\n"]
[[6, 0, 0], 16.666666666666664, {"submitted": 1589640512.899966, "started": 1589640512.9000628, "finished": 1589640513.2083569}, null, "Traceback (most recent call last):\n  File \"/home/shuki/anaconda3/envs/CAVE/lib/python3.8/site-packages/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/home/shuki/Repos/Auto-PyTorch/autoPyTorch/core/worker.py\", line 86, in compute\n    raise Exception(\"Exception in train pipeline. Took \" + str((time.time()-start_time)) + \" seconds with budget \" + str(budget))\nException: Exception in train pipeline. Took 0.30205345153808594 seconds with budget 16.666666666666664\n"]
[[6, 0, 1], 16.666666666666664, {"submitted": 1589640513.2140982, "started": 1589640513.214181, "finished": 1589640513.6872396}, null, "Traceback (most recent call last):\n  File \"/home/shuki/anaconda3/envs/CAVE/lib/python3.8/site-packages/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/home/shuki/Repos/Auto-PyTorch/autoPyTorch/core/worker.py\", line 86, in compute\n    raise Exception(\"Exception in train pipeline. Took \" + str((time.time()-start_time)) + \" seconds with budget \" + str(budget))\nException: Exception in train pipeline. Took 0.4668905735015869 seconds with budget 16.666666666666664\n"]
[[6, 0, 2], 16.666666666666664, {"submitted": 1589640513.695241, "started": 1589640513.6953902, "finished": 1589640521.7523882}, {"loss": -76.77777777777779, "info": {"loss": 0.5703772753477097, "model_parameters": 54940.0, "lr_scheduler_converged": 0.0, "lr": 0.00028440763332644985, "train_accuracy": 72.22222222222221, "val_accuracy": 77.77777777777779, "test_result": 79.0, "test_cross_entropy": 0.6381025910377502, "test_balanced_accuracy": 0.7738095238095237}}, null]
[[6, 0, 2], 50.0, {"submitted": 1589640521.7580657, "started": 1589640521.7581599, "finished": 1589640563.666943}, {"loss": -75.66666666666667, "info": {"loss": 0.28468331694602966, "model_parameters": 54940.0, "lr_scheduler_converged": 0.0, "lr": 0.00011291959339994324, "train_accuracy": 89.74358974358975, "val_accuracy": 76.66666666666667, "test_result": 66.0, "test_cross_entropy": 0.578906774520874, "test_balanced_accuracy": 0.7071428571428571}}, null]
[[7, 0, 0], 50.0, {"submitted": 1589640563.672753, "started": 1589640563.672864, "finished": 1589640564.2121325}, null, "Traceback (most recent call last):\n  File \"/home/shuki/anaconda3/envs/CAVE/lib/python3.8/site-packages/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/home/shuki/Repos/Auto-PyTorch/autoPyTorch/core/worker.py\", line 86, in compute\n    raise Exception(\"Exception in train pipeline. Took \" + str((time.time()-start_time)) + \" seconds with budget \" + str(budget))\nException: Exception in train pipeline. Took 0.5351581573486328 seconds with budget 50.0\n"]
[[7, 0, 1], 50.0, {"submitted": 1589640564.2213385, "started": 1589640564.2215064, "finished": 1589640564.7269948}, null, "Traceback (most recent call last):\n  File \"/home/shuki/anaconda3/envs/CAVE/lib/python3.8/site-packages/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/home/shuki/Repos/Auto-PyTorch/autoPyTorch/core/worker.py\", line 86, in compute\n    raise Exception(\"Exception in train pipeline. Took \" + str((time.time()-start_time)) + \" seconds with budget \" + str(budget))\nException: Exception in train pipeline. Took 0.49580812454223633 seconds with budget 50.0\n"]
[[8, 0, 0], 16.666666666666664, {"submitted": 1589640564.739067, "started": 1589640564.7393658, "finished": 1589640572.7368493}, {"loss": -66.77777777777779, "info": {"loss": 0.6448108702898026, "model_parameters": 832835.0, "lr_scheduler_converged": 0.0, "lr": 0.00023828667384417196, "train_accuracy": 60.88709677419355, "val_accuracy": 67.77777777777779, "test_result": 62.0, "test_cross_entropy": 0.6511846780776978, "test_balanced_accuracy": 0.6142857142857143}}, null]
[[8, 0, 1], 16.666666666666664, {"submitted": 1589640572.7412956, "started": 1589640572.7413633, "finished": 1589640573.1776586}, null, "Traceback (most recent call last):\n  File \"/home/shuki/anaconda3/envs/CAVE/lib/python3.8/site-packages/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/home/shuki/Repos/Auto-PyTorch/autoPyTorch/core/worker.py\", line 86, in compute\n    raise Exception(\"Exception in train pipeline. Took \" + str((time.time()-start_time)) + \" seconds with budget \" + str(budget))\nException: Exception in train pipeline. Took 0.42969274520874023 seconds with budget 16.666666666666664\n"]
[[8, 0, 2], 16.666666666666664, {"submitted": 1589640573.1886299, "started": 1589640573.1887934, "finished": 1589640573.4870687}, null, "Traceback (most recent call last):\n  File \"/home/shuki/anaconda3/envs/CAVE/lib/python3.8/site-packages/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/home/shuki/Repos/Auto-PyTorch/autoPyTorch/core/worker.py\", line 86, in compute\n    raise Exception(\"Exception in train pipeline. Took \" + str((time.time()-start_time)) + \" seconds with budget \" + str(budget))\nException: Exception in train pipeline. Took 0.29402589797973633 seconds with budget 16.666666666666664\n"]
[[8, 0, 0], 50.0, {"submitted": 1589640573.49992, "started": 1589640573.5001853, "finished": 1589640614.8532465}, {"loss": -74.55555555555556, "info": {"loss": 0.58990198969841, "model_parameters": 832835.0, "lr_scheduler_converged": 0.0, "lr": 0.00023526642886876898, "train_accuracy": 60.322580645161295, "val_accuracy": 75.55555555555556, "test_result": 65.0, "test_cross_entropy": 0.6299378275871277, "test_balanced_accuracy": 0.7119047619047619}}, null]
[[9, 0, 0], 50.0, {"submitted": 1589640614.8571558, "started": 1589640614.8572214, "finished": 1589640615.1275842}, null, "Traceback (most recent call last):\n  File \"/home/shuki/anaconda3/envs/CAVE/lib/python3.8/site-packages/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/home/shuki/Repos/Auto-PyTorch/autoPyTorch/core/worker.py\", line 86, in compute\n    raise Exception(\"Exception in train pipeline. Took \" + str((time.time()-start_time)) + \" seconds with budget \" + str(budget))\nException: Exception in train pipeline. Took 0.2666170597076416 seconds with budget 50.0\n"]
[[9, 0, 1], 50.0, {"submitted": 1589640615.1406217, "started": 1589640615.1407657, "finished": 1589640615.549446}, null, "Traceback (most recent call last):\n  File \"/home/shuki/anaconda3/envs/CAVE/lib/python3.8/site-packages/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/home/shuki/Repos/Auto-PyTorch/autoPyTorch/core/worker.py\", line 86, in compute\n    raise Exception(\"Exception in train pipeline. Took \" + str((time.time()-start_time)) + \" seconds with budget \" + str(budget))\nException: Exception in train pipeline. Took 0.40409255027770996 seconds with budget 50.0\n"]
[[10, 0, 0], 16.666666666666664, {"submitted": 1589640615.5583792, "started": 1589640615.5585632, "finished": 1589640615.895047}, null, "Traceback (most recent call last):\n  File \"/home/shuki/anaconda3/envs/CAVE/lib/python3.8/site-packages/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/home/shuki/Repos/Auto-PyTorch/autoPyTorch/core/worker.py\", line 86, in compute\n    raise Exception(\"Exception in train pipeline. Took \" + str((time.time()-start_time)) + \" seconds with budget \" + str(budget))\nException: Exception in train pipeline. Took 0.3312394618988037 seconds with budget 16.666666666666664\n"]
[[10, 0, 1], 16.666666666666664, {"submitted": 1589640615.9007864, "started": 1589640615.900867, "finished": 1589640616.2159872}, null, "Traceback (most recent call last):\n  File \"/home/shuki/anaconda3/envs/CAVE/lib/python3.8/site-packages/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/home/shuki/Repos/Auto-PyTorch/autoPyTorch/core/worker.py\", line 86, in compute\n    raise Exception(\"Exception in train pipeline. Took \" + str((time.time()-start_time)) + \" seconds with budget \" + str(budget))\nException: Exception in train pipeline. Took 0.3105447292327881 seconds with budget 16.666666666666664\n"]
[[10, 0, 2], 16.666666666666664, {"submitted": 1589640616.2225776, "started": 1589640616.2230089, "finished": 1589640616.5654283}, null, "Traceback (most recent call last):\n  File \"/home/shuki/anaconda3/envs/CAVE/lib/python3.8/site-packages/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/home/shuki/Repos/Auto-PyTorch/autoPyTorch/core/worker.py\", line 86, in compute\n    raise Exception(\"Exception in train pipeline. Took \" + str((time.time()-start_time)) + \" seconds with budget \" + str(budget))\nException: Exception in train pipeline. Took 0.33854150772094727 seconds with budget 16.666666666666664\n"]
[[10, 1, 0], 50.0, {"submitted": 1589640616.5748947, "started": 1589640616.5749788, "finished": 1589640616.9725318}, null, "Traceback (most recent call last):\n  File \"/home/shuki/anaconda3/envs/CAVE/lib/python3.8/site-packages/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/home/shuki/Repos/Auto-PyTorch/autoPyTorch/core/worker.py\", line 86, in compute\n    raise Exception(\"Exception in train pipeline. Took \" + str((time.time()-start_time)) + \" seconds with budget \" + str(budget))\nException: Exception in train pipeline. Took 0.392958402633667 seconds with budget 50.0\n"]
[[11, 0, 0], 50.0, {"submitted": 1589640616.9783444, "started": 1589640616.97845, "finished": 1589640617.323689}, null, "Traceback (most recent call last):\n  File \"/home/shuki/anaconda3/envs/CAVE/lib/python3.8/site-packages/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/home/shuki/Repos/Auto-PyTorch/autoPyTorch/core/worker.py\", line 86, in compute\n    raise Exception(\"Exception in train pipeline. Took \" + str((time.time()-start_time)) + \" seconds with budget \" + str(budget))\nException: Exception in train pipeline. Took 0.33608269691467285 seconds with budget 50.0\n"]
[[11, 0, 1], 50.0, {"submitted": 1589640617.3306432, "started": 1589640617.3310177, "finished": 1589640617.6550431}, null, "Traceback (most recent call last):\n  File \"/home/shuki/anaconda3/envs/CAVE/lib/python3.8/site-packages/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/home/shuki/Repos/Auto-PyTorch/autoPyTorch/core/worker.py\", line 86, in compute\n    raise Exception(\"Exception in train pipeline. Took \" + str((time.time()-start_time)) + \" seconds with budget \" + str(budget))\nException: Exception in train pipeline. Took 0.31865406036376953 seconds with budget 50.0\n"]
[[12, 0, 0], 16.666666666666664, {"submitted": 1589640617.6649663, "started": 1589640617.6651082, "finished": 1589640625.6624284}, {"loss": -75.66666666666667, "info": {"loss": 0.6937521261828287, "model_parameters": 1363608.0, "lr_scheduler_converged": 0.0, "lr": 0.0007961144712028326, "train_accuracy": 50.476190476190474, "val_accuracy": 76.66666666666667, "test_result": 75.0, "test_cross_entropy": 0.6421357989311218, "test_balanced_accuracy": 0.7642857142857142}}, null]
[[12, 0, 1], 16.666666666666664, {"submitted": 1589640625.666657, "started": 1589640625.6667218, "finished": 1589640626.067502}, null, "Traceback (most recent call last):\n  File \"/home/shuki/anaconda3/envs/CAVE/lib/python3.8/site-packages/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/home/shuki/Repos/Auto-PyTorch/autoPyTorch/core/worker.py\", line 86, in compute\n    raise Exception(\"Exception in train pipeline. Took \" + str((time.time()-start_time)) + \" seconds with budget \" + str(budget))\nException: Exception in train pipeline. Took 0.3938133716583252 seconds with budget 16.666666666666664\n"]
[[12, 0, 2], 16.666666666666664, {"submitted": 1589640626.0739806, "started": 1589640626.0740736, "finished": 1589640634.6791947}, {"loss": -67.51851851851852, "info": {"loss": 0.9060764908790588, "model_parameters": 6365819.0, "lr_scheduler_converged": 0.0, "lr": 0.010019328967185765, "train_accuracy": 69.88636363636364, "val_accuracy": 68.51851851851852, "test_result": 70.0, "test_cross_entropy": 0.6683632135391235, "test_balanced_accuracy": 0.5}}, null]
[[12, 0, 0], 50.0, {"submitted": 1589640634.6812408, "started": 1589640634.6813138, "finished": 1589640676.0570335}, {"loss": -66.03703703703704, "info": {"loss": 0.627090334892273, "model_parameters": 1363608.0, "lr_scheduler_converged": 0.0, "lr": 0.0007553601396371037, "train_accuracy": 64.91228070175438, "val_accuracy": 67.03703703703704, "test_result": 66.0, "test_cross_entropy": 0.6670024991035461, "test_balanced_accuracy": 0.6523809523809523}}, null]
[[13, 0, 0], 50.0, {"submitted": 1589640676.060759, "started": 1589640676.0608225, "finished": 1589640676.4435115}, null, "Traceback (most recent call last):\n  File \"/home/shuki/anaconda3/envs/CAVE/lib/python3.8/site-packages/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/home/shuki/Repos/Auto-PyTorch/autoPyTorch/core/worker.py\", line 86, in compute\n    raise Exception(\"Exception in train pipeline. Took \" + str((time.time()-start_time)) + \" seconds with budget \" + str(budget))\nException: Exception in train pipeline. Took 0.37920331954956055 seconds with budget 50.0\n"]
[[13, 0, 1], 50.0, {"submitted": 1589640676.4514284, "started": 1589640676.4515598, "finished": 1589640676.9978626}, null, "Traceback (most recent call last):\n  File \"/home/shuki/anaconda3/envs/CAVE/lib/python3.8/site-packages/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/home/shuki/Repos/Auto-PyTorch/autoPyTorch/core/worker.py\", line 86, in compute\n    raise Exception(\"Exception in train pipeline. Took \" + str((time.time()-start_time)) + \" seconds with budget \" + str(budget))\nException: Exception in train pipeline. Took 0.5394012928009033 seconds with budget 50.0\n"]
[[14, 0, 0], 16.666666666666664, {"submitted": 1589640677.006, "started": 1589640677.0060883, "finished": 1589640677.341551}, null, "Traceback (most recent call last):\n  File \"/home/shuki/anaconda3/envs/CAVE/lib/python3.8/site-packages/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/home/shuki/Repos/Auto-PyTorch/autoPyTorch/core/worker.py\", line 86, in compute\n    raise Exception(\"Exception in train pipeline. Took \" + str((time.time()-start_time)) + \" seconds with budget \" + str(budget))\nException: Exception in train pipeline. Took 0.32997608184814453 seconds with budget 16.666666666666664\n"]
[[14, 0, 1], 16.666666666666664, {"submitted": 1589640677.3477, "started": 1589640677.347821, "finished": 1589640677.664794}, null, "Traceback (most recent call last):\n  File \"/home/shuki/anaconda3/envs/CAVE/lib/python3.8/site-packages/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/home/shuki/Repos/Auto-PyTorch/autoPyTorch/core/worker.py\", line 86, in compute\n    raise Exception(\"Exception in train pipeline. Took \" + str((time.time()-start_time)) + \" seconds with budget \" + str(budget))\nException: Exception in train pipeline. Took 0.31275033950805664 seconds with budget 16.666666666666664\n"]
[[14, 0, 2], 16.666666666666664, {"submitted": 1589640677.6722975, "started": 1589640677.6723797, "finished": 1589640678.0543032}, null, "Traceback (most recent call last):\n  File \"/home/shuki/anaconda3/envs/CAVE/lib/python3.8/site-packages/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/home/shuki/Repos/Auto-PyTorch/autoPyTorch/core/worker.py\", line 86, in compute\n    raise Exception(\"Exception in train pipeline. Took \" + str((time.time()-start_time)) + \" seconds with budget \" + str(budget))\nException: Exception in train pipeline. Took 0.37766337394714355 seconds with budget 16.666666666666664\n"]
[[14, 1, 0], 50.0, {"submitted": 1589640678.0619152, "started": 1589640678.0620718, "finished": 1589640678.3427522}, null, "Traceback (most recent call last):\n  File \"/home/shuki/anaconda3/envs/CAVE/lib/python3.8/site-packages/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/home/shuki/Repos/Auto-PyTorch/autoPyTorch/core/worker.py\", line 86, in compute\n    raise Exception(\"Exception in train pipeline. Took \" + str((time.time()-start_time)) + \" seconds with budget \" + str(budget))\nException: Exception in train pipeline. Took 0.27444982528686523 seconds with budget 50.0\n"]
[[15, 0, 0], 50.0, {"submitted": 1589640678.3505664, "started": 1589640678.3506567, "finished": 1589640678.653457}, null, "Traceback (most recent call last):\n  File \"/home/shuki/anaconda3/envs/CAVE/lib/python3.8/site-packages/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/home/shuki/Repos/Auto-PyTorch/autoPyTorch/core/worker.py\", line 86, in compute\n    raise Exception(\"Exception in train pipeline. Took \" + str((time.time()-start_time)) + \" seconds with budget \" + str(budget))\nException: Exception in train pipeline. Took 0.29891085624694824 seconds with budget 50.0\n"]
[[15, 0, 1], 50.0, {"submitted": 1589640678.663269, "started": 1589640678.6634252, "finished": 1589640679.0032995}, null, "Traceback (most recent call last):\n  File \"/home/shuki/anaconda3/envs/CAVE/lib/python3.8/site-packages/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/home/shuki/Repos/Auto-PyTorch/autoPyTorch/core/worker.py\", line 86, in compute\n    raise Exception(\"Exception in train pipeline. Took \" + str((time.time()-start_time)) + \" seconds with budget \" + str(budget))\nException: Exception in train pipeline. Took 0.33341479301452637 seconds with budget 50.0\n"]
[[16, 0, 0], 16.666666666666664, {"submitted": 1589640679.0117207, "started": 1589640679.011932, "finished": 1589640687.0258837}, {"loss": -69.37037037037037, "info": {"loss": 0.5619816184043884, "model_parameters": 20162.0, "lr_scheduler_converged": 0.0, "lr": 0.015680502317024846, "train_accuracy": 61.711711711711715, "val_accuracy": 70.37037037037037, "test_result": 63.0, "test_cross_entropy": 0.6382045149803162, "test_balanced_accuracy": 0.7071428571428571}}, null]
[[16, 0, 1], 16.666666666666664, {"submitted": 1589640687.033996, "started": 1589640687.0340788, "finished": 1589640687.4001095}, null, "Traceback (most recent call last):\n  File \"/home/shuki/anaconda3/envs/CAVE/lib/python3.8/site-packages/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/home/shuki/Repos/Auto-PyTorch/autoPyTorch/core/worker.py\", line 86, in compute\n    raise Exception(\"Exception in train pipeline. Took \" + str((time.time()-start_time)) + \" seconds with budget \" + str(budget))\nException: Exception in train pipeline. Took 0.36173272132873535 seconds with budget 16.666666666666664\n"]
[[16, 0, 2], 16.666666666666664, {"submitted": 1589640687.4120314, "started": 1589640687.4121578, "finished": 1589640687.6902337}, null, "Traceback (most recent call last):\n  File \"/home/shuki/anaconda3/envs/CAVE/lib/python3.8/site-packages/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/home/shuki/Repos/Auto-PyTorch/autoPyTorch/core/worker.py\", line 86, in compute\n    raise Exception(\"Exception in train pipeline. Took \" + str((time.time()-start_time)) + \" seconds with budget \" + str(budget))\nException: Exception in train pipeline. Took 0.2727360725402832 seconds with budget 16.666666666666664\n"]
[[16, 0, 0], 50.0, {"submitted": 1589640687.6932693, "started": 1589640687.6933546, "finished": 1589640728.9979172}, {"loss": -67.51851851851852, "info": {"loss": 0.4716741979122162, "model_parameters": 20162.0, "lr_scheduler_converged": 0.0, "lr": 0.013989090382734127, "train_accuracy": 71.89189189189189, "val_accuracy": 68.51851851851852, "test_result": 72.0, "test_cross_entropy": 0.6025912761688232, "test_balanced_accuracy": 0.7333333333333334}}, null]
[[17, 0, 0], 50.0, {"submitted": 1589640729.0019147, "started": 1589640729.0019798, "finished": 1589640729.3760254}, null, "Traceback (most recent call last):\n  File \"/home/shuki/anaconda3/envs/CAVE/lib/python3.8/site-packages/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/home/shuki/Repos/Auto-PyTorch/autoPyTorch/core/worker.py\", line 86, in compute\n    raise Exception(\"Exception in train pipeline. Took \" + str((time.time()-start_time)) + \" seconds with budget \" + str(budget))\nException: Exception in train pipeline. Took 0.3696315288543701 seconds with budget 50.0\n"]
[[17, 0, 1], 50.0, {"submitted": 1589640729.38957, "started": 1589640729.3897038, "finished": 1589640729.923989}, null, "Traceback (most recent call last):\n  File \"/home/shuki/anaconda3/envs/CAVE/lib/python3.8/site-packages/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/home/shuki/Repos/Auto-PyTorch/autoPyTorch/core/worker.py\", line 86, in compute\n    raise Exception(\"Exception in train pipeline. Took \" + str((time.time()-start_time)) + \" seconds with budget \" + str(budget))\nException: Exception in train pipeline. Took 0.5290577411651611 seconds with budget 50.0\n"]
[[18, 0, 0], 16.666666666666664, {"submitted": 1589640729.9300067, "started": 1589640729.9301982, "finished": 1589640730.3362198}, null, "Traceback (most recent call last):\n  File \"/home/shuki/anaconda3/envs/CAVE/lib/python3.8/site-packages/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/home/shuki/Repos/Auto-PyTorch/autoPyTorch/core/worker.py\", line 86, in compute\n    raise Exception(\"Exception in train pipeline. Took \" + str((time.time()-start_time)) + \" seconds with budget \" + str(budget))\nException: Exception in train pipeline. Took 0.40108418464660645 seconds with budget 16.666666666666664\n"]
[[18, 0, 1], 16.666666666666664, {"submitted": 1589640730.3449454, "started": 1589640730.345037, "finished": 1589640730.6701336}, null, "Traceback (most recent call last):\n  File \"/home/shuki/anaconda3/envs/CAVE/lib/python3.8/site-packages/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/home/shuki/Repos/Auto-PyTorch/autoPyTorch/core/worker.py\", line 86, in compute\n    raise Exception(\"Exception in train pipeline. Took \" + str((time.time()-start_time)) + \" seconds with budget \" + str(budget))\nException: Exception in train pipeline. Took 0.32123541831970215 seconds with budget 16.666666666666664\n"]
[[18, 0, 2], 16.666666666666664, {"submitted": 1589640730.6765065, "started": 1589640730.676598, "finished": 1589640731.1861382}, null, "Traceback (most recent call last):\n  File \"/home/shuki/anaconda3/envs/CAVE/lib/python3.8/site-packages/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/home/shuki/Repos/Auto-PyTorch/autoPyTorch/core/worker.py\", line 86, in compute\n    raise Exception(\"Exception in train pipeline. Took \" + str((time.time()-start_time)) + \" seconds with budget \" + str(budget))\nException: Exception in train pipeline. Took 0.5053491592407227 seconds with budget 16.666666666666664\n"]
[[18, 1, 0], 50.0, {"submitted": 1589640731.1913674, "started": 1589640731.1914756, "finished": 1589640731.6084082}, null, "Traceback (most recent call last):\n  File \"/home/shuki/anaconda3/envs/CAVE/lib/python3.8/site-packages/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/home/shuki/Repos/Auto-PyTorch/autoPyTorch/core/worker.py\", line 86, in compute\n    raise Exception(\"Exception in train pipeline. Took \" + str((time.time()-start_time)) + \" seconds with budget \" + str(budget))\nException: Exception in train pipeline. Took 0.4124298095703125 seconds with budget 50.0\n"]
[[19, 0, 0], 50.0, {"submitted": 1589640731.6179323, "started": 1589640731.6180615, "finished": 1589640772.955727}, {"loss": -71.5925925925926, "info": {"loss": 0.5999532540639242, "model_parameters": 10986.0, "lr_scheduler_converged": 0.0, "lr": 0.00022082507095051395, "train_accuracy": 66.66666666666666, "val_accuracy": 72.5925925925926, "test_result": 65.0, "test_cross_entropy": 0.6132681369781494, "test_balanced_accuracy": 0.6880952380952381}}, null]
[[19, 0, 1], 50.0, {"submitted": 1589640772.9593394, "started": 1589640772.959415, "finished": 1589640773.2623427}, null, "Traceback (most recent call last):\n  File \"/home/shuki/anaconda3/envs/CAVE/lib/python3.8/site-packages/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/home/shuki/Repos/Auto-PyTorch/autoPyTorch/core/worker.py\", line 86, in compute\n    raise Exception(\"Exception in train pipeline. Took \" + str((time.time()-start_time)) + \" seconds with budget \" + str(budget))\nException: Exception in train pipeline. Took 0.29918861389160156 seconds with budget 50.0\n"]
[[20, 0, 0], 16.666666666666664, {"submitted": 1589640773.2707493, "started": 1589640773.2708504, "finished": 1589640773.672083}, null, "Traceback (most recent call last):\n  File \"/home/shuki/anaconda3/envs/CAVE/lib/python3.8/site-packages/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/home/shuki/Repos/Auto-PyTorch/autoPyTorch/core/worker.py\", line 86, in compute\n    raise Exception(\"Exception in train pipeline. Took \" + str((time.time()-start_time)) + \" seconds with budget \" + str(budget))\nException: Exception in train pipeline. Took 0.39432287216186523 seconds with budget 16.666666666666664\n"]
[[20, 0, 1], 16.666666666666664, {"submitted": 1589640773.6799245, "started": 1589640773.680016, "finished": 1589640774.1177807}, null, "Traceback (most recent call last):\n  File \"/home/shuki/anaconda3/envs/CAVE/lib/python3.8/site-packages/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/home/shuki/Repos/Auto-PyTorch/autoPyTorch/core/worker.py\", line 86, in compute\n    raise Exception(\"Exception in train pipeline. Took \" + str((time.time()-start_time)) + \" seconds with budget \" + str(budget))\nException: Exception in train pipeline. Took 0.43302154541015625 seconds with budget 16.666666666666664\n"]
[[20, 0, 2], 16.666666666666664, {"submitted": 1589640774.1253874, "started": 1589640774.1255288, "finished": 1589640774.5186434}, null, "Traceback (most recent call last):\n  File \"/home/shuki/anaconda3/envs/CAVE/lib/python3.8/site-packages/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/home/shuki/Repos/Auto-PyTorch/autoPyTorch/core/worker.py\", line 86, in compute\n    raise Exception(\"Exception in train pipeline. Took \" + str((time.time()-start_time)) + \" seconds with budget \" + str(budget))\nException: Exception in train pipeline. Took 0.3870244026184082 seconds with budget 16.666666666666664\n"]
[[20, 1, 0], 50.0, {"submitted": 1589640774.5288045, "started": 1589640774.5288906, "finished": 1589640815.8334835}, {"loss": -66.4074074074074, "info": {"loss": 0.04926466206236491, "model_parameters": 25128.0, "lr_scheduler_converged": 0.0, "lr": 1.6421430788512705e-05, "train_accuracy": 100.0, "val_accuracy": 67.4074074074074, "test_result": 71.0, "test_cross_entropy": 0.6838092803955078, "test_balanced_accuracy": 0.6785714285714286}}, null]
[[21, 0, 0], 50.0, {"submitted": 1589640815.8377469, "started": 1589640815.8378103, "finished": 1589640816.2492998}, null, "Traceback (most recent call last):\n  File \"/home/shuki/anaconda3/envs/CAVE/lib/python3.8/site-packages/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/home/shuki/Repos/Auto-PyTorch/autoPyTorch/core/worker.py\", line 86, in compute\n    raise Exception(\"Exception in train pipeline. Took \" + str((time.time()-start_time)) + \" seconds with budget \" + str(budget))\nException: Exception in train pipeline. Took 0.40749192237854004 seconds with budget 50.0\n"]
[[21, 0, 1], 50.0, {"submitted": 1589640816.2591727, "started": 1589640816.259484, "finished": 1589640857.5472844}, {"loss": -76.77777777777779, "info": {"loss": 0.5243842601776123, "model_parameters": 9194.0, "lr_scheduler_converged": 0.0, "lr": 0.0009223136551684537, "train_accuracy": 74.59677419354838, "val_accuracy": 77.77777777777779, "test_result": 80.0, "test_cross_entropy": 0.5646916031837463, "test_balanced_accuracy": 0.7333333333333334}}, null]
[[22, 0, 0], 16.666666666666664, {"submitted": 1589640857.551656, "started": 1589640857.5517244, "finished": 1589640857.8609536}, null, "Traceback (most recent call last):\n  File \"/home/shuki/anaconda3/envs/CAVE/lib/python3.8/site-packages/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/home/shuki/Repos/Auto-PyTorch/autoPyTorch/core/worker.py\", line 86, in compute\n    raise Exception(\"Exception in train pipeline. Took \" + str((time.time()-start_time)) + \" seconds with budget \" + str(budget))\nException: Exception in train pipeline. Took 0.3055145740509033 seconds with budget 16.666666666666664\n"]
[[22, 0, 1], 16.666666666666664, {"submitted": 1589640857.8717816, "started": 1589640857.8719263, "finished": 1589640858.1710758}, null, "Traceback (most recent call last):\n  File \"/home/shuki/anaconda3/envs/CAVE/lib/python3.8/site-packages/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/home/shuki/Repos/Auto-PyTorch/autoPyTorch/core/worker.py\", line 86, in compute\n    raise Exception(\"Exception in train pipeline. Took \" + str((time.time()-start_time)) + \" seconds with budget \" + str(budget))\nException: Exception in train pipeline. Took 0.29032230377197266 seconds with budget 16.666666666666664\n"]
[[22, 0, 2], 16.666666666666664, {"submitted": 1589640858.1809983, "started": 1589640858.1811523, "finished": 1589640866.8885293}, {"loss": -67.51851851851852, "info": {"loss": 0.6288386881351471, "model_parameters": 1890538.0, "lr_scheduler_converged": 0.0, "lr": 0.02786831670609786, "train_accuracy": 66.92307692307692, "val_accuracy": 68.51851851851852, "test_result": 70.0, "test_cross_entropy": 0.6537309885025024, "test_balanced_accuracy": 0.5}}, null]
[[22, 0, 2], 50.0, {"submitted": 1589640866.8907418, "started": 1589640866.890822, "finished": 1589640908.6225972}, {"loss": -67.51851851851852, "info": {"loss": 0.5538177873407092, "model_parameters": 1890538.0, "lr_scheduler_converged": 0.0, "lr": 0.0278173050395452, "train_accuracy": 68.57142857142857, "val_accuracy": 68.51851851851852, "test_result": 70.0, "test_cross_entropy": 0.6298903226852417, "test_balanced_accuracy": 0.5}}, null]
[[23, 0, 0], 50.0, {"submitted": 1589640908.6263952, "started": 1589640908.6264632, "finished": 1589640949.8929877}, {"loss": -67.51851851851852, "info": {"loss": 0.6932433156740098, "model_parameters": 13343.0, "lr_scheduler_converged": 0.0, "lr": 0.04809363856749901, "train_accuracy": 37.301587301587304, "val_accuracy": 68.51851851851852, "test_result": 70.0, "test_cross_entropy": 0.6907707452774048, "test_balanced_accuracy": 0.5}}, null]
[[23, 0, 1], 50.0, {"submitted": 1589640949.8974314, "started": 1589640949.897509, "finished": 1589640950.1952682}, null, "Traceback (most recent call last):\n  File \"/home/shuki/anaconda3/envs/CAVE/lib/python3.8/site-packages/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/home/shuki/Repos/Auto-PyTorch/autoPyTorch/core/worker.py\", line 86, in compute\n    raise Exception(\"Exception in train pipeline. Took \" + str((time.time()-start_time)) + \" seconds with budget \" + str(budget))\nException: Exception in train pipeline. Took 0.29397106170654297 seconds with budget 50.0\n"]
[[24, 0, 0], 16.666666666666664, {"submitted": 1589640950.2118967, "started": 1589640950.212089, "finished": 1589640950.543888}, null, "Traceback (most recent call last):\n  File \"/home/shuki/anaconda3/envs/CAVE/lib/python3.8/site-packages/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/home/shuki/Repos/Auto-PyTorch/autoPyTorch/core/worker.py\", line 86, in compute\n    raise Exception(\"Exception in train pipeline. Took \" + str((time.time()-start_time)) + \" seconds with budget \" + str(budget))\nException: Exception in train pipeline. Took 0.32651233673095703 seconds with budget 16.666666666666664\n"]
[[24, 0, 1], 16.666666666666664, {"submitted": 1589640950.5502822, "started": 1589640950.550371, "finished": 1589640950.9276695}, null, "Traceback (most recent call last):\n  File \"/home/shuki/anaconda3/envs/CAVE/lib/python3.8/site-packages/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/home/shuki/Repos/Auto-PyTorch/autoPyTorch/core/worker.py\", line 86, in compute\n    raise Exception(\"Exception in train pipeline. Took \" + str((time.time()-start_time)) + \" seconds with budget \" + str(budget))\nException: Exception in train pipeline. Took 0.37361764907836914 seconds with budget 16.666666666666664\n"]
[[24, 0, 2], 16.666666666666664, {"submitted": 1589640950.943142, "started": 1589640950.9432573, "finished": 1589640951.2711878}, null, "Traceback (most recent call last):\n  File \"/home/shuki/anaconda3/envs/CAVE/lib/python3.8/site-packages/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/home/shuki/Repos/Auto-PyTorch/autoPyTorch/core/worker.py\", line 86, in compute\n    raise Exception(\"Exception in train pipeline. Took \" + str((time.time()-start_time)) + \" seconds with budget \" + str(budget))\nException: Exception in train pipeline. Took 0.3232574462890625 seconds with budget 16.666666666666664\n"]
[[24, 1, 0], 50.0, {"submitted": 1589640951.2808495, "started": 1589640951.2809649, "finished": 1589640951.639711}, null, "Traceback (most recent call last):\n  File \"/home/shuki/anaconda3/envs/CAVE/lib/python3.8/site-packages/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/home/shuki/Repos/Auto-PyTorch/autoPyTorch/core/worker.py\", line 86, in compute\n    raise Exception(\"Exception in train pipeline. Took \" + str((time.time()-start_time)) + \" seconds with budget \" + str(budget))\nException: Exception in train pipeline. Took 0.35222864151000977 seconds with budget 50.0\n"]
[[25, 0, 0], 50.0, {"submitted": 1589640951.6500037, "started": 1589640951.650107, "finished": 1589640952.097238}, null, "Traceback (most recent call last):\n  File \"/home/shuki/anaconda3/envs/CAVE/lib/python3.8/site-packages/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/home/shuki/Repos/Auto-PyTorch/autoPyTorch/core/worker.py\", line 86, in compute\n    raise Exception(\"Exception in train pipeline. Took \" + str((time.time()-start_time)) + \" seconds with budget \" + str(budget))\nException: Exception in train pipeline. Took 0.44161438941955566 seconds with budget 50.0\n"]
[[25, 0, 1], 50.0, {"submitted": 1589640952.1037884, "started": 1589640952.1038876, "finished": 1589640952.3871794}, null, "Traceback (most recent call last):\n  File \"/home/shuki/anaconda3/envs/CAVE/lib/python3.8/site-packages/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/home/shuki/Repos/Auto-PyTorch/autoPyTorch/core/worker.py\", line 86, in compute\n    raise Exception(\"Exception in train pipeline. Took \" + str((time.time()-start_time)) + \" seconds with budget \" + str(budget))\nException: Exception in train pipeline. Took 0.27882933616638184 seconds with budget 50.0\n"]
[[26, 0, 0], 16.666666666666664, {"submitted": 1589640952.3989248, "started": 1589640952.3990853, "finished": 1589640952.7681925}, null, "Traceback (most recent call last):\n  File \"/home/shuki/anaconda3/envs/CAVE/lib/python3.8/site-packages/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/home/shuki/Repos/Auto-PyTorch/autoPyTorch/core/worker.py\", line 86, in compute\n    raise Exception(\"Exception in train pipeline. Took \" + str((time.time()-start_time)) + \" seconds with budget \" + str(budget))\nException: Exception in train pipeline. Took 0.353748083114624 seconds with budget 16.666666666666664\n"]
[[26, 0, 1], 16.666666666666664, {"submitted": 1589640952.7762392, "started": 1589640952.776331, "finished": 1589640953.1333776}, null, "Traceback (most recent call last):\n  File \"/home/shuki/anaconda3/envs/CAVE/lib/python3.8/site-packages/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/home/shuki/Repos/Auto-PyTorch/autoPyTorch/core/worker.py\", line 86, in compute\n    raise Exception(\"Exception in train pipeline. Took \" + str((time.time()-start_time)) + \" seconds with budget \" + str(budget))\nException: Exception in train pipeline. Took 0.3523218631744385 seconds with budget 16.666666666666664\n"]
[[26, 0, 2], 16.666666666666664, {"submitted": 1589640953.1440148, "started": 1589640953.14413, "finished": 1589640961.1365728}, {"loss": -74.92592592592592, "info": {"loss": 0.4792155474424362, "model_parameters": 631996.0, "lr_scheduler_converged": 0.0, "lr": 0.014862739548335972, "train_accuracy": 76.34920634920634, "val_accuracy": 75.92592592592592, "test_result": 73.0, "test_cross_entropy": 0.564698338508606, "test_balanced_accuracy": 0.7595238095238095}}, null]
[[26, 0, 2], 50.0, {"submitted": 1589640961.1382887, "started": 1589640961.1383548, "finished": 1589641002.4240599}, {"loss": -72.70370370370371, "info": {"loss": 0.06587380170822144, "model_parameters": 631996.0, "lr_scheduler_converged": 0.0, "lr": 0.008814714785162764, "train_accuracy": 99.04761904761905, "val_accuracy": 73.70370370370371, "test_result": 72.0, "test_cross_entropy": 0.5825961828231812, "test_balanced_accuracy": 0.6571428571428571}}, null]
[[27, 0, 0], 50.0, {"submitted": 1589641002.4284186, "started": 1589641002.4284935, "finished": 1589641002.7720854}, null, "Traceback (most recent call last):\n  File \"/home/shuki/anaconda3/envs/CAVE/lib/python3.8/site-packages/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/home/shuki/Repos/Auto-PyTorch/autoPyTorch/core/worker.py\", line 86, in compute\n    raise Exception(\"Exception in train pipeline. Took \" + str((time.time()-start_time)) + \" seconds with budget \" + str(budget))\nException: Exception in train pipeline. Took 0.33895158767700195 seconds with budget 50.0\n"]
[[27, 0, 1], 50.0, {"submitted": 1589641002.7804158, "started": 1589641002.7806327, "finished": 1589641003.4040632}, null, "Traceback (most recent call last):\n  File \"/home/shuki/anaconda3/envs/CAVE/lib/python3.8/site-packages/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/home/shuki/Repos/Auto-PyTorch/autoPyTorch/core/worker.py\", line 86, in compute\n    raise Exception(\"Exception in train pipeline. Took \" + str((time.time()-start_time)) + \" seconds with budget \" + str(budget))\nException: Exception in train pipeline. Took 0.615443229675293 seconds with budget 50.0\n"]
[[28, 0, 0], 16.666666666666664, {"submitted": 1589641003.4135482, "started": 1589641003.413669, "finished": 1589641011.3921704}, {"loss": -67.51851851851852, "info": {"loss": 0.6190734505653381, "model_parameters": 56773.0, "lr_scheduler_converged": 0.0, "lr": 0.07458134094298097, "train_accuracy": 69.45945945945947, "val_accuracy": 68.51851851851852, "test_result": 70.0, "test_cross_entropy": 0.642890453338623, "test_balanced_accuracy": 0.5}}, null]
[[28, 0, 1], 16.666666666666664, {"submitted": 1589641011.396906, "started": 1589641011.396994, "finished": 1589641011.703787}, null, "Traceback (most recent call last):\n  File \"/home/shuki/anaconda3/envs/CAVE/lib/python3.8/site-packages/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/home/shuki/Repos/Auto-PyTorch/autoPyTorch/core/worker.py\", line 86, in compute\n    raise Exception(\"Exception in train pipeline. Took \" + str((time.time()-start_time)) + \" seconds with budget \" + str(budget))\nException: Exception in train pipeline. Took 0.30256199836730957 seconds with budget 16.666666666666664\n"]
[[28, 0, 2], 16.666666666666664, {"submitted": 1589641011.7102368, "started": 1589641011.710318, "finished": 1589641011.9801493}, null, "Traceback (most recent call last):\n  File \"/home/shuki/anaconda3/envs/CAVE/lib/python3.8/site-packages/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/home/shuki/Repos/Auto-PyTorch/autoPyTorch/core/worker.py\", line 86, in compute\n    raise Exception(\"Exception in train pipeline. Took \" + str((time.time()-start_time)) + \" seconds with budget \" + str(budget))\nException: Exception in train pipeline. Took 0.264284610748291 seconds with budget 16.666666666666664\n"]
[[28, 0, 0], 50.0, {"submitted": 1589641011.9856734, "started": 1589641011.9913588, "finished": 1589641053.395182}, {"loss": -67.51851851851852, "info": {"loss": 0.6073325810924409, "model_parameters": 56773.0, "lr_scheduler_converged": 0.0, "lr": 0.0698941758119446, "train_accuracy": 70.63492063492063, "val_accuracy": 68.51851851851852, "test_result": 70.0, "test_cross_entropy": 0.637744128704071, "test_balanced_accuracy": 0.5}}, null]
